// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fqfreawnvqtxjpgzlntz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxZnJlYXdudnF0eGpwZ3psbnR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzU4OTksImV4cCI6MjA3MDI1MTg5OX0.IAmpuXsjK6oUwnTzA1gWDP2yP95tEuJ6tLf5ERrQ_g4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);